### ISSUE TITLE
How to break “RabbitMQ Delayed Delivery” for all endpoints

### ISSUE THREAD

**Issue by rebchr** [Particular/NServiceBus.RabbitMQ#1407] opened 2024-06-11 08:41 UTC
### Describe the suggested improvement

Using NServiceBus v 8.2.0 + NServiceBus.RabbitMQ

Steps to reproduce:
1.	Endpoint “Endpoint1” requires a timeout or delayed message in 5 minutes
2.	Uninstall/remove “Endpoint1” and the corresponding Exchange and Queue on Rabbit
3.	When the delayed message expires all the way down to the “nsb.v2.delay-delivery” exchange it will no longer have a valid destination, and it will get stuck in the last queue (e.g  nsb.v2.delay-level-08) marked as deadlettered. Messages dead-lettered with dead-letter-strategy at-least-once are not moved from the source queue until it is acked by the destination-queue (https://www.rabbitmq.com/docs/quorum-queues#dead-lettering)
4.	The consequence is that all delayed messages going through the nsb.v2.delay-level-08 queue will get forever stuck.

The fix: Recreate the Exchange and queue for “Endpoint1”, and do not remove them until you are sure that all pending delayed messages has timed out and reached the Endpoint1-queue.

I don’t know if you would consider this a bug, but it sure is a thing worth mentioning in the [documentation](https://docs.particular.net/transports/rabbitmq/delayed-delivery). It’s difficult to debug (since messages in this state cannot be peeked), and it affects the entire delayed-messaging-infrastructure.

### Additional Context

RabbitMQ 3.10.10
Conventional routing topology (classic queues)

**Comment by jpalac** [comment] 2024-06-14 06:09
Could you please tell us what version of RabbitMQ you are running? 
We have tried reproducing this with 3.10.7 and have not been able to.

**Comment by rebchr** [comment] 2024-06-17 08:05
RabbitMQ version 3.10.10

Tried upgrading our staging env to 3.10.25. Same result

**Comment by jpalac** [comment] 2024-06-18 22:48
Let me summarise my code and steps below.

I am running:
- RabbitMQ v3.10.25
  - nsb.v2.delay-level queues have `x-dead-letter-strategy` as `at-least-once`
- NServiceBus 8.*
- NServiceBus.RabbitMQ 8.*
- RabbitMQ.Client 6.*


This is the sender code I have:

```
var endpointConfiguration = new EndpointConfiguration("RabbitMQ.Sender");
var transport = endpointConfiguration.UseTransport<RabbitMQTransport>();
transport.UseConventionalRoutingTopology(QueueType.Quorum);
transport.ConnectionString("myconnection");

transport.Routing().RouteToEndpoint(assembly: Assembly.GetAssembly(typeof(MyCommand)), "RabbitMQ.Receiver");
endpointConfiguration.UseSerialization<SystemJsonSerializer>();
endpointConfiguration.EnableInstallers();

var endpointInstance = await Endpoint.Start(endpointConfiguration);
await SendMessages(endpointInstance);
await endpointInstance.Stop();

static async Task SendMessages(IMessageSession messageSession)
{
    Console.WriteLine("Press [s] to send a command, or [p] to publish an event, or [d] to delay a message. Press [Esc] to exit.");
    while (true)
    {
        var input = Console.ReadKey();
        Console.WriteLine();

        switch (input.Key)
        {
            case ConsoleKey.S:
                await messageSession.Send(new MyCommand());
                break;
            case ConsoleKey.P:
                await messageSession.Publish(new MyEvent());
                break;
            case ConsoleKey.D:
                var sendOptions = new SendOptions();

                sendOptions.DelayDeliveryWith(TimeSpan.FromSeconds(30));
                await messageSession.Send(new MyDelayedMessage(), sendOptions);
                break;
            case ConsoleKey.Escape:
                return;
        }
    }
}
```

And receiver:

```
var endpointConfiguration = new EndpointConfiguration("RabbitMQ.Receiver");
var transport = endpointConfiguration.UseTransport<RabbitMQTransport>();
transport.UseConventionalRoutingTopology(QueueType.Quorum);
transport.ConnectionString("myconnection");
endpointConfiguration.UseSerialization<SystemJsonSerializer>();            
endpointConfiguration.EnableInstallers();

var endpointInstance = await Endpoint.Start(endpointConfiguration);
Console.WriteLine("Press any key to exit");
Console.ReadKey();
await endpointInstance.Stop();
```

After sending a couple of delayed messages, I:
- stop both endpoints
- deleteRabbitMQ.Receiver queue from the broker
- delete RabbitMQ.Receiver exchange from the broker
- wait for the delayed messages to be end up in nsb.v2.delay-level-01 queue as dead lettered

Then to send a new set of delayed messages, I:
- change the receiver endpoint to be RabbitMQ.Receiver2
- change the routing on the sender to go to RabbitMQ.Receiver2
- start both endpoints
- send a couple of delayed messages
- wait for them to travel through to nsb.v2.delay-level-01, at which point they are delivered to the Receiver2 endpoint

Please let me know if your setup differs to mine.

**Comment by jpalac** [comment] 2024-06-25 02:57
Closing for now as we were unable to reproduce it. The issue can be reopened if more information is received.

**Closed by jpalac** 2024-06-25 02:57 UTC
Labels: Improvement
