### ISSUE TITLE
Nservicebus.rabbitmq 3.5.1 Transport incorrectly includes machine name when displaying an Address

### ISSUE THREAD

**Issue by sandeep44** [Particular/NServiceBus.RabbitMQ#434] opened 2017-09-26 09:01 UTC
Hi
I am facing a issue in Nservicebus.rabbitmq 3.5.1 that Transport incorrectly includes machine name when displaying an Address.Reply-to address not being set correctly. My services our on different machine .

Please help

**Comment by WojcikMike** [comment] 2017-09-26 09:23
@sandeep44 can you please provide more details? Where do you view Reply-to address containing machine name (in ServicePulse, in ServiceInsight or in code?). What action do you try to make and how it fails?

**Comment by sandeep44** [comment] 2017-09-26 09:29
I have webapi and 2 window services. My webapi is hosted on different machine say machine-01 and window services are hosted in different machine say machine-02, now i have provided the queue address in web.config file of my webapi. lets say workerservice@machine-02. worker service respond to my another backbone service, i have already defined the path of backbone service queue in web.config the same like i did for worker that is backboneservice@machine-02. but with this version of Nservicebus.rabbitmq 3.5.1. my backbone service wrongly pointed to backboneservice@machine-01 (the address where my webapi is hosted). It was working fine with the version Nservicebus.rabbitmq 3.3.1.

please let me know if you need more detail

**Comment by WojcikMike** [comment] 2017-09-27 12:12
Thank you for clarification @sandeep44 

First and foremost the naming convention of queueName@machineName is used in MSMQ and should not be used in RabbitMQ. The reason for that is that Rabbit is a broker (1 centralized component) so no endpoint needs to know anything about where another endpoint is deployed. The only interesting piece is the queueName as this is where the messages will be sent. Later on, consumer reads messages from that queue. So I would like to recommend eliminating @machine** from all queue address when using Rabbit or any other broker transport.

Rabbit in version 3.* uses NServiceBus v5 which represents queue address as a class Address. This class contains information about queue name and the machine name. Machine name in Rabbit is ignored however in the past there were situations when machine name was visible in logs (and as the machine name was never set, the class returned current machine name). That is in terms of explanation.

The solution is to not use @machineName in the queue address and everything should work fine. Please let me know if this helped in your case.

**Comment by sandeep44** [comment] 2017-10-02 06:41
Hi,

A request message has failed. Its NServiceBus.ReplyToAddress header has the following (correct) value SendingEndpoint@SendingEndpointMachine.testing.domain. 
After I retry the message (using MSMQ  in Handlor class), its ReplyToAddress header is now overwritten with: SendingEndpoint@ServiceControlMachine, and the message is put on the receiver endpoint's queue. As part of processing this message, we do a Bus.Reply, and the logs from the processing endpoint indicate that the response message is sent to the wrong queue (SendingEndpoint@ServiceControlMachine). I would expect that the response message would be sent to SendingEndpoint@SendingEndpointMachine.testing.domain

Can someone help me with this issue?

We use:
NServiceBus 5.2.21

**Comment by WojcikMike** [comment] 2017-10-02 09:51
@sandeep44 could you please raise a ticket using https://particular.net/support
I think that setting one call together would clarify this issue a lot.

**Comment by WojcikMike** [comment] 2017-10-31 14:56
@sandeep44 any success with creating a ticket? I couldn't see one from you (yet I could have missed it)

**Comment by WojcikMike** [comment] 2017-11-18 11:35
@sandeep44 Once again I recommend contacting support to solve this issue. I will close this issues, as there are not enough details to understand what the problem is. We can reopen the issues after a support call happen and exact problem is identified.

**Closed by WojcikMike** 2017-11-18 11:35 UTC
