### ISSUE TITLE
Autoack can cause message loss during shutdown

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.RabbitMQ#122] opened 2016-01-28 05:21 UTC
Task force: @bording @WojcikMike

When auto-acknowledgements are turned on, the server acknowledges the message as soon as it is sent to the client. 

RabbitMQ uses the `BasicQos()` method as its server->client flow control mechanism. You set the `prefechCount` parameter to tell the server how many unacknowledged messages to send the client before it waits to send more. If you've turned on auto-acknowledgements, that means you've effectively turned off flow control, because you never have unacknowledged messages.

This means that those messages build up in-memory in the RabbitMQ client, waiting for us to process them. If we then shut down the endpoint with those messages still unprocessed, they are lost because they've already been acknowledged on the server.

Currently, we turn auto-acknowledgements on whenever an endpoint has been configured to not use transactions (for example, `TransportTransactionMode.None` in v6).

I'm not really sure why auto-acknowledgements has been tied to transaction settings. They don't really feel like related concepts. Based on how acknowledgements are used for flow control, I don't think we should ever turn on auto-acknowledgements.

One additional problem related to using auto-acknowledgements mode is that you can potentially hit an out of memory scenario.

Since the server is sending messages as soon as it gets them without any sort of rate control, if an endpoint is too slow at processing them, the buffer that the RabbitMQ client is storing the messages in could potentially fill up and throw an OutOfMemoryException:

rabbitmq/rabbitmq-dotnet-client#123

----

Original comment

@bording can u expand on this

**Comment by mauroservienti** [comment] 2016-01-29 14:53
If I recall correctly when autoAck is on messages are acknowledged in the Q as they are picked up and then stored in a in memory Q by the RabbitMQ client waiting to be processed. Given that they are in memory and acknowledged to the broker if the endpoint shuts down or crashes those messages are lost.

**Comment by mauroservienti** [comment] 2016-01-29 14:53
should we consider this in scope for V6? if yes, could you please ad the expected label? cheers.

**Comment by andreasohlund** [comment] 2016-01-29 14:59
If it's message loss shouldn't we fix it in the current version + backport?

**Comment by mauroservienti** [comment] 2016-01-29 15:02
@andreasohlund agree, we should fix it. IIRC the autoAck is turned on, in the actual production version, when the user disables transactions. @bording proposal is to keep if off regardless of the transaction settings.

**Comment by andreasohlund** [comment] 2016-01-29 15:16
>when the user disables transactions

In that case I'd say we don't need to backport since tx off means that you will loose messages anyway?

But of course we should not have code that contributes further to message loss.

**Comment by mauroservienti** [comment] 2016-01-29 15:22
> In that case I'd say we don't need to backport since tx off means that you will loose messages anyway?

I disagree because:

> But of course we should not have code that contributes further to message loss.

:smile:

**Comment by bording** [comment] 2016-01-29 17:33
As @mauroservienti mentioned, when auto-acknowledgements are turned on, the server acknowledges the message as soon as it is sent to the client. 

RabbitMQ uses the `BasicQos()` method as its server->client flow control mechanism. You set the `prefechCount` parameter to tell the server how many unacknowledged messages to send the client before it waits to send more. If you've turned on auto-acknowledgements, that means you've effectively turned off flow control, because you never have unacknowledged messages.

This means that those messages build up in-memory in the RabbitMQ client, waiting for us to process them. If we then shut down the endpoint with those messages still unprocessed, they are lost because they've already been acknowledged on the server.

Currently, we turn auto-acknowledgements on whenever an endpoint has been configured to not use transactions (for example, `TransportTransactionMode.None` in v6).

I'm not really sure why auto-acknowledgements has been tied to transaction settings. They don't really feel like related concepts. Based on how acknowledgements are used for flow control, I don't think we should ever turn on auto-acknowledgements.

**Comment by andreasohlund** [comment] 2016-01-30 06:36
@mauroservienti good point I'm contradicting my self :)

@bording how likely is this to cause extra message loss?

:+1: to fix for current version just trying to figure out if we need to backport

**Comment by bording** [comment] 2016-01-30 07:03
If you have auto-acknowledgements enabled and you shutdown an endpoint that is busy receiving messages, you will lose some, guaranteed. The busier the endpoint, the more messages you'll lose.

To avoid that, when an endpoint is shutting down we would have to cancel the consumer, and then continue to process all remaining messages until the in-memory buffer in the RabbitMQ client was empty. This doesn't seem like a viable option since it could leave the endpoint running for an unknown amount of time while trying to shut down.

When using manual acknowledgements, we can just shut down normally, and any unprocessed messages end up back on the queue since we never send a BasicAck for them.

**Comment by andreasohlund** [comment] 2016-01-30 07:09
Ok, that seems to be a fairly large amount of message loss :(

:+1: to fix and backport

**Comment by andreasohlund** [comment] 2016-02-01 20:43
At least 3.0.x , do we want to go further back?

**Comment by andreasohlund** [comment] 2016-02-29 18:57
@bording can you get this into the `release-3.1.0` branch as well?

**Comment by bording** [comment] 2016-02-29 22:06
ffc0629 Fixes this in `release-3.1.0`.

**Comment by bording** [comment] 2016-03-09 20:36
One additional problem related to using auto-acknowledgements mode that I'd like to point out is that you can potentially hit an out of memory scenario.

Since the server is sending messages as soon as it gets them without any sort of rate control, if an endpoint is too slow at processing them, the buffer that the RabbitMQ client is storing the messages in could potentially fill up and throw an OutOfMemoryException:

https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/123

**Comment by andreasohlund** [comment] 2016-03-16 12:53
@bording moved this one into in progress since I know that you're working on it

**Comment by WojcikMike** [comment] 2016-03-22 14:36
Btw. the issue is well described in this blog post: https://wheleph.github.io/2015/06/27/on-rabbitmq-automatic-ack-and-reliable-message-processing/ 

The code is in Java, but the problem is presented well.

**Comment by danielmarbach** [comment] 2016-03-24 10:02
@Particular/transport-maintainers It seems it is only @bording working on this. Can we get a TF formed and get this going?

**Comment by mauroservienti** [comment] 2016-03-24 10:05
Updated the description, @WojcikMike do you want to join? if yes add yourself to the TF

**Comment by WojcikMike** [comment] 2016-03-24 11:59
> Updated the description, @WojcikMike do you want to join? if yes add yourself to the TF
Done

**Comment by bording** [comment] 2016-03-24 21:07
So, as I mentioned [here](https://github.com/Particular/NServiceBus.RabbitMQ/issues/122#issuecomment-178172851), the code on `develop` is no longer using auto-ack, so this could have been considered done then.

However, before I closed it, I wanted to look into making some additional changes based on the conclusions from https://github.com/Particular/NServiceBus/issues/3581 around how `TransportTransactionMode.None` should be handled.

I spent some time investigating moving the acknowledgement to before processing the message, but doing this led me down and never-ending rabbit hole (pun intended!) of refactoring and and additional complexity. After talking with @danielmarbach today about it, I think the best thing to do for now is to leave the current implementation unchanged. The extra complexity being introduced just to accommodate moving the ack before processing didn't seem worth it at this time.

For the v6 launch at least, I think it makes the most sense to continue to treat `None` the same as `ReceiveOnly` instead of trying to support a separate `None` that RabbitMQ is fighting me from actually being able to implement.

Thoughts? Anyone object to me closing this?

**Comment by andreasohlund** [comment] 2016-03-24 22:00
Only thing that comes to mind is timing out the receives? (is there a receive timeout in Rabbit)

Since None== should never timeout
          ReceiveOnly == times out when the receive TX takes to long

The reason I bring it up is that we've told user in the past to turn transactions of if they have long running handlers

**Comment by bording** [comment] 2016-03-24 22:15
There isn't any sort of receive timeout in Rabbit. As long as the channel stays open, the broker will wait for ack messages. It's only when the channel is closed when it will requeue any messages that haven't been acked.

**Comment by mauroservienti** [comment] 2016-03-25 07:15
So basically we're saying that in RabbitMQ we could consider `None` the same as `ReceiveOnly` and since we have no timeout, unless we build our custom one, we could say that RabbitMQ supports `None` and cannot support `ReceiveOnly`.

**Comment by andreasohlund** [comment] 2016-03-27 10:57
@bording what would happen if in "none" we ack messages no matter what (ie do a try catch around the push)

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessagePump.cs#L157

and ignore the abort flag 

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessagePump.cs#L161


and for "receive only" we ack on success just like we do today?

**Comment by bording** [comment] 2016-03-28 23:58
@andreasohlund I'm not sure that would actually change anything. From what I understand, we should no longer see an exception thrown from the push, or at least I've never seen an exception thrown while working on this.

FLR retry is indicated by the cancellation token being canceled, so since FLR is disabled when in `none` mode the result should already be what you're proposing: always ack the message.

**Comment by bording** [comment] 2016-03-29 00:06
> Since None== should never timeout
ReceiveOnly == times out when the receive TX takes to long

@andreasohlund I found this interesting, because this statement of behavior was new to me. How is this enforced? Is it something core does, or is the transport responsible?

I talked with @SeanFeldman about this, and we went and took a look at the code around pushing a message from the transport and into core. The conclusion we came to is that for this behavior to happen, core is assuming a `TransportTransaction` that contains a transaction with a timeout would be passed in from the transport.

Assuming we understand correctly how this is working, then it seems like we might have an issue for all transports that don't actually use transactions. Rabbit, ASB, and ASQ all mimic the various transaction modes without actually having a transaction to pass to core.

**Comment by andreasohlund** [comment] 2016-03-29 05:58
@bording Let's get on a call with @SeanFeldman and hash this out. I'll make it happen

Side note: None should IMO not do any retries so acking the message no matter what seem appropriate for that reason as well?

**Comment by andreasohlund** [comment] 2016-03-29 18:49
Talking to @bording and @SeanFeldman we concluded that the timeouts we where talking about was from a transport perspective. Ie transactionmode.none == no timeout from a transport perspective.

This bring up the question of what to do with handlers that never complete?

There is already an [issue raised for this](https://github.com/Particular/NServiceBus/issues/3423), I will setup a call for next week when @danielmarbach is back to discuss this further.

**Closed** 2016-03-29 18:49 UTC
Labels: Project: V6 Launch, State: In Progress, Type: Bug

**Comment by johnsimons** [comment] 2016-05-04 00:47
@bording was this fixed in v4 ?
What do we need to document ?

**Comment by bording** [comment] 2016-05-04 00:59
> @bording was this fixed in v4 ?
What do we need to document ?

Yes, it was fixed in the V4 message pump by always using auto-ack. It's already been documented [here](http://docs.particular.net/nservicebus/rabbitmq/configuration-api#transactions-and-delivery-guarantees).
