### ISSUE TITLE
Replace IManageRabbitMqConnections with a better extension point

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RabbitMQ#88] opened 2015-05-20 00:21 UTC
There is just too much usage of internal classes to call this a valid extension point

**Comment by andreasohlund** [comment] 2015-05-20 11:18
Agreed, I think we should obsolete it?

**Comment by SzymonPobiega** [comment] 2015-06-01 09:38
Duplicate of #74

**Closed by SzymonPobiega** 2015-06-01 09:38 UTC
Labels: Improvement
