### ISSUE TITLE
Allow client certificate authentication with an external auth mechanism

### ISSUE THREAD

**Issue by dagapitov** [Particular/NServiceBus.RabbitMQ#407] opened 2017-07-31 21:08 UTC
I'm trying to configure NServiceBus (v 6.3.4) with RabbitMQ transport (v 4.3.2) to use client certificate authentication instead of user/password based but getting authentication error (Error: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.)

RabbitMQ instance is configured to support TLS and client certificates auth and it's working fine when RabbitMQ.Client library is used directly as in the next [example](https://github.com/dagapitov/nsb-certificate-auth/blob/master/RabbitmqAuthTest/Program.cs).

Similar configuration with NServiceBus library doesn't work as expected (see https://github.com/dagapitov/nsb-certificate-auth/blob/master/NsbRabbitmqAuthTest/Program.cs).

It looks like NSB rabbitmq transport always use 'Plain' authentication mechanism and I cannot find a way to override this behaviour for ConnectionFactory (similar to RabbitMQ.Client - https://github.com/dagapitov/nsb-certificate-auth/blob/master/RabbitmqAuthTest/Program.cs#L24) 

## Plan of attack

- [x] make changes - #430
- [ ] update docs - https://github.com/Particular/docs.particular.net/pull/3218

**Comment by bording** [comment] 2017-07-31 23:27
@dagapitov Thanks for reporting this! You're correct, looks like the RabbitMQ client [doesn't include the EXTERNAL auth mechanism option by default](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L147...L148), so we need to add it when we create our connection factory.

We should be able to add this and a get a fix out for you soon!

**Comment by dagapitov** [comment] 2017-08-02 15:57
@bording Thank you. Do you have any timeline when this fix will be available?

**Comment by bording** [comment] 2017-08-02 23:44
@dagapitov There's no specific ETA yet. We have already have a 6.3.3 hotfix that should be going out tomorrow, so this fix would likely be in a 4.3.4 release.

**Comment by adamralph** [comment] 2017-09-01 10:41
We came to the conclusion that this is not a bug, but rather the lack of a feature, i.e. allowing the use of external auth mechanisms. Re-labelling and re-titling.

**Comment by bording** [comment] 2017-09-14 18:31
This will be in the 4.4.0 release.

**Closed by bording** 2017-09-14 18:31 UTC

**Comment by bording** [comment] 2017-09-18 19:57
@dagapitov 4.4.0 has been released and here is the documentation on the new setting: https://docs.particular.net/transports/rabbitmq/connection-settings#transport-layer-security-support-external-authentication
