### ISSUE TITLE
Message fails to be forwarded to the error queue

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#102] opened 2015-09-22 18:51 UTC
User report on the group 

```
Product name: NServiceBus.RabbitMQ
Version: 2.1.2
Stacktrace: 

Could not forward failed message to error queue.

RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=501, text="FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,180101,131064}", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirms(TimeSpan timeout, Boolean& timedOut)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie(TimeSpan timeout)
   at NServiceBus.Transports.RabbitMQ.ConfirmsAwareChannel.Dispose() in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\ConfirmsAwareChannel.cs:line 55
   at NServiceBus.Transports.RabbitMQ.RabbitMqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqMessageSender.cs:line 27
   at NServiceBus.Faults.Forwarder.FaultManager.HandleProcessingAlwaysFailsForMessage(TransportMessage message, Exception e, Int32 numberOfRetries) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 90
   at NServiceBus.Faults.Forwarder.FaultManager.<>c__DisplayClass4.<NServiceBus.Faults.IManageMessageFailures.ProcessingAlwaysFailsForMessage>b__3() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 43
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 112

another exception that occurred before was...

Fault manager failed to process the failed message with id d6c32246-4938-4b15-94bf-a51b00cecb44

System.InvalidOperationException: Could not forward failed message to error queue. ---> RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=501, text="FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,180101,131064}", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirms(TimeSpan timeout, Boolean& timedOut)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie(TimeSpan timeout)
   at NServiceBus.Transports.RabbitMQ.ConfirmsAwareChannel.Dispose() in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\ConfirmsAwareChannel.cs:line 55
   at NServiceBus.Transports.RabbitMQ.RabbitMqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqMessageSender.cs:line 27
   at NServiceBus.Faults.Forwarder.FaultManager.HandleProcessingAlwaysFailsForMessage(TransportMessage message, Exception e, Int32 numberOfRetries) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 90
   at NServiceBus.Faults.Forwarder.FaultManager.<>c__DisplayClass4.<NServiceBus.Faults.IManageMessageFailures.ProcessingAlwaysFailsForMessage>b__3() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 43
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 112
   --- End of inner exception stack trace ---
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 124
   at NServiceBus.Unicast.Transport.FirstLevelRetries.TryInvokeFaultManager(TransportMessage message, Exception exception, Int32 numberOfAttempts) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\FirstLevelRetries.cs:line 66

Description:

We send a pretty large payload over rabbitMQ (multiple MBs in size). The handler picks up the message successfully, processes it, but fails multiple times. The message is then attempting to go to the error queue, but unsuccessful. My guess is that the forwarding of the message to the error queue isn't taking into account the potential size of the payload?

```

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/50AM1lFpgCw/iY893JrXBAAJ

**Comment by andreasohlund** [comment] 2015-09-22 18:52
I wonder if the extra headers we attach when forwarding to the error queue causes the size to go over the limit. 

Seems like the error can happen for other reasons as well

http://john.eckersberg.com/debugging-rabbitmq-frame_too_large-error.html

@adamralph would you be able to try to repro this?

**Comment by burkhartt** [comment] 2015-09-22 19:25
I have some more insight into this. Another time it happened, these were the exceptions:

<pre>Could not forward failed message to error queue.
RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=501, text="FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,160084,131064}", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply()
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)
   at RabbitMQ.Client.Framing.Impl.Connection.CreateModel()
   at NServiceBus.Transports.RabbitMQ.ChannelProvider.GetNewPublishChannel() in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\ChannelProvider.cs:line 35
   at NServiceBus.Transports.RabbitMQ.RabbitMqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqMessageSender.cs:line 25
   at NServiceBus.Faults.Forwarder.FaultManager.HandleProcessingAlwaysFailsForMessage(TransportMessage message, Exception e, Int32 numberOfRetries) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 90
   at NServiceBus.Faults.Forwarder.FaultManager.<>c__DisplayClass4.<NServiceBus.Faults.IManageMessageFailures.ProcessingAlwaysFailsForMessage>b__3() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 43
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 112

</pre>

and 

<pre>
Fault manager failed to process the failed message with id 07ea36b2-a223-4bd9-9d9b-a50f010e5d76

System.InvalidOperationException: Could not forward failed message to error queue. ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=501, text="FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,160084,131064}", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply()
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)
   at RabbitMQ.Client.Framing.Impl.Connection.CreateModel()
   at NServiceBus.Transports.RabbitMQ.ChannelProvider.GetNewPublishChannel() in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\ChannelProvider.cs:line 35
   at NServiceBus.Transports.RabbitMQ.RabbitMqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqMessageSender.cs:line 25
   at NServiceBus.Faults.Forwarder.FaultManager.HandleProcessingAlwaysFailsForMessage(TransportMessage message, Exception e, Int32 numberOfRetries) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 90
   at NServiceBus.Faults.Forwarder.FaultManager.<>c__DisplayClass4.<NServiceBus.Faults.IManageMessageFailures.ProcessingAlwaysFailsForMessage>b__3() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 43
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 112
   --- End of inner exception stack trace ---
   at NServiceBus.Faults.Forwarder.FaultManager.TryHandleFailure(Action failureHandlingAction) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Faults\Forwarder\FaultManager.cs:line 124
   at NServiceBus.Unicast.Transport.FirstLevelRetries.TryInvokeFaultManager(TransportMessage message, Exception exception, Int32 numberOfAttempts) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\FirstLevelRetries.cs:line 66
</pre>

But the seemingly unique thing about this is that the payload is very small (it's just a single Guid). However, the handler makes a call to salesforce using a large payload (a few MBs) and salesforce throws an exception. The exception contains the full body of the payload, which makes it back into NServiceBus's log message:

<pre>
Retry 2 - HEADERS: [NServiceBus.MessageId] -- 07ea36b2-a223-4bd9-9d9b-a50f010e5d76 ........... [NServiceBus.CorrelationId] -- 07ea36b2-a223-4bd9-9d9b-a50f010e5d76 ........... [NServiceBus.MessageIntent] -- Send ........... [NServiceBus.Version] -- 5.2.0 ........... [NServiceBus.TimeSent] -- 2015-09-10 20:24:22:148242 Z ........... [NServiceBus.ContentType] -- text/xml ........... [NServiceBus.EnclosedMessageTypes] -- Engine.Messages.SalesForce.BookingPublishedForCrmCommand2, Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ........... [NServiceBus.ConversationId] -- 81dab46b-fe50-459a-9479-a50f010e5d76 ........... [WinIdName] -- James.Simone ........... [Session.User.Identity.Name] -- James.Simone ........... [Country] --  ........... [NServiceBus.OriginatingMachine] -- USAM-GATQAWEB1 ........... [NServiceBus.OriginatingEndpoint] -- WebServiceUSAM-GATQAWEB1 ........... [$.diagnostics.originating.hostid] -- 71c96d8bcc8a9b278577dfe20a2c2abd ........... [NServiceBus.RabbitMQ.CallbackQueue] -- WebServiceUSAM-GATQAWEB1.USAM-GATQAWEB1 ........... [NServiceBus.ReplyToAddress] -- WebServiceUSAM-GATQAWEB1 ........... [$.diagnostics.hostid] -- b138c9febc56e4c29b4ddd363adc4fa0 ........... [$.diagnostics.hostdisplayname] -- USAM-GATQAWEB1 - BODY: System.Byte[] - MESSAGE: Post https://gat--QA.cs19.my.salesforce.com/services/apexrest/orders
With data:
 LARGE JSON DATA WAS HERE. OMITTED FOR BREVITY.
</pre>

I'm not sure if this is the issue, but since I can see these information in ServicePulse, my guess is that it is getting passed along inside of RabbitMQ at some point...

**Comment by andreasohlund** [comment] 2015-09-22 19:34
That seems to reinforce my hunch, since we don't cap the exception details we put into the headers. We'll try to repro this on our end!

**Comment by burkhartt** [comment] 2015-10-05 15:40
Do you have a time estimate for when there will be a fix for this?

**Comment by adamralph** [comment] 2015-10-05 16:02
hi @burkhartt

Sorry for the delay, I actually managed to reproduce the same error message today by putting a large message on an exception and throwing it from a handler.

When you say...

> The exception contains the full body of the payload

...is that in the exception message? I.e `Exception.Message` property?

If so, one thing we could do is add a facility to configure the maximum length of the exception message which is added to the headers of the message which is sent to the error queue. We would use this value to truncate the message before adding it to the headers. We would default this to `int.MaxValue` in order that there is no initial effect, and you can then reduce it to a value which works for your scenario. What do you think?

**Comment by adamralph** [comment] 2015-10-05 16:11
Issue repro - https://github.com/Particular/NServiceBus.RabbitMQ-Issue-102

**Comment by burkhartt** [comment] 2015-10-05 16:16
Yea the exception is in the exception.message property. I suppose that option will work. The other option is for us to just not have a massive exception in the first place but having nservicebus at least protect against the message size in rabbitmq is also a good option. So I'm ok with that route.

**Comment by adamralph** [comment] 2015-10-05 16:37
@burkhartt OK, I'll see if I can get the feature added. Note that this feature is independent of which transport is being used so it will be a new feature in NServiceBus itself rather than NServiceBus.RabbitMQ.

In the meantime, if urgency requires it, I guess you could work around it by catching the exception and throwing a new one with a truncated message.

For reference this is the output produced by my repro -https://gist.github.com/adamralph/4e83a850530c2ce96f48

**Comment by adamralph** [comment] 2015-10-05 17:03
@Particular/nservicebus I propose that we close this bug as a `wontfix` since we can't predict the size of exception message which will make each transport refuse the error message, and instead lean on https://github.com/Particular/NServiceBus/issues/2953 as a feature which allows the user to tune the behaviour of our error message generation to avoid this problem.

Thoughts?

**Comment by SeanFeldman** [comment] 2015-10-05 17:29
Sounds like a right approach.

**Comment by burkhartt** [comment] 2015-10-05 17:39
Yep we are going to do that. Thanks for your help!

**Comment by adamralph** [comment] 2015-10-05 17:58
Or alternatively, we could spin off an immediate patch to limit the exception message to, say, 2 ^ 15 (seeing as the repro only breaks at 2 ^ 16) and then later the new feature will arrive to make it configurable.

**Comment by burkhartt** [comment] 2015-10-05 18:00
From my perspective that works.

**Comment by adamralph** [comment] 2015-10-06 07:42
@andreasohlund what are your thoughts on that?

On second thoughts I'd probably make the hard limit 2 ^ 14, since we know 2 ^ 15 works and that will give 2 ^13 space for the rest of the message (which will probably enough for anyone :wink:).

**Comment by adamralph** [comment] 2015-10-06 08:46
Moving this issue to https://github.com/Particular/NServiceBus/issues/2956

**Closed by adamralph** 2015-10-06 08:46 UTC
Labels: State: Getting Ready, Type: Bug

**Comment by adamralph** [comment] 2015-10-06 14:15
@burkhartt the fix has been released, please see https://github.com/Particular/NServiceBus/issues/2956#issuecomment-145869787

**Comment by burkhartt** [comment] 2015-10-06 14:16
Great thanks! We will give it a shot!

**Comment by adamralph** [comment] 2015-10-13 11:06
hi @burkhartt, just checking in - how did this work out for you? Did NServiceBus 5.2.7 fix the problem for you?

**Comment by burkhartt** [comment] 2015-10-13 11:17
Yep looked like it worked. Thanks!!
