### ISSUE TITLE
Use of multiple brokers cause a object disposed exception

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#85] opened 2015-04-22 06:31 UTC
### User report
I'm having a problem configuring RabbitMQ with multiple brokers. My configuration is 

```xml
<add name="NServiceBus/Transport"
    connectionString="host=broker1,broker2;username=clusteradmin;password=123456" /> 
 
  <TransportConfig MaximumConcurrencyLevel="10" />
  <UnicastBusConfig>
    <MessageEndpointMappings>
      <add Assembly="Domain" Namespace="Domain.Messages" Endpoint="NServiceBus.Services" />
    </MessageEndpointMappings>
  </UnicastBusConfig>
  <AuditConfig QueueName="audit" />

```

Each server works correctly on their own, ie if I change my connection string to

```xml
<add name="NServiceBus/Transport"
    connectionString="host=broker1;username=clusteradmin;password=123456" /> 
```
or 
```xml
<add name="NServiceBus/Transport"
    connectionString="host=broker2;username=clusteradmin;password=123456" /> 
````

However with both brokers in the connection the first call happens successfully while all other get a "System.ObjectDisposedException: Cannot access a disposed object." I inject the bus as a SingleInstance with autofac for the mvc application. 
, I've read up that NServiceBus round robbins these connections to the different hosts, so I'm guessing it disposes of the first connection to broker1 but then doesn't make the connection to broker2 ? 

 (the RabbitMQ brokers have NOT been configured in any sort of cluster I'm not sure if there is any advantage to setting up a cluster as I assume NServiceBus will handle failed nodes and reties of given message in the event that a particar node goes down, with its persistance model)

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'UnicastBus'.
   at NServiceBus.Unicast.UnicastBus.Send(Object message)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

**Comment by janovesk** [comment] 2015-04-27 08:56
Originally from https://groups.google.com/forum/#!searchin/particularsoftware/Each$20server$20works$20correctly$20on$20their$20own/particularsoftware/48DyrtIO5iw/H1NWeyjMYKkJ

**Comment by janovesk** [comment] 2015-04-28 14:19
I'm having trouble reproducing this. Asked the original poster for a reproduction.

**Comment by andreasohlund** [comment] 2015-05-19 06:30
@janovesk did you get a response?

**Comment by andreasohlund** [comment] 2015-05-20 11:28
Will be fixed in 3.0.0 since we're deprecating the multi connection string thing

**Comment by bording** [comment] 2016-03-24 22:43
Since 3.0.0 and multi-broker support has been removed, I'm going to close this as fixed.

**Closed by bording** 2016-03-24 22:43 UTC
Labels: Type: Bug

**Comment by adamralph** [comment] 2016-11-08 17:39
Changing status to withdrawn. The multi-broker feature was removed in 3.0 so it does not exist in that version, and we will not be fixing this in older versions.
